### ISSUE TITLE
UI to leave comments on whole chunk and chapters

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/8woc2017#119]
## User Story
As a user, I want the ability to record an audio comment on a chunk or a chapter so that I can communicate feedback to others. 

## Acceptance Criteria
- [x] UI to record an audio comment on a chunk
- [x] UI to record an audio comment on a chapter

**Comment by sheesania** [comment]
@erica-zhong @dvmarchuk We also need to list comments from the database that are associated with a particular chapter or chunk, and have them available to play. Do you want to make that part of this story or make a new one?

**Comment by erica-zhong** [comment]
@sheesania @dvmarchuk lets make a new story for that? because its involved with the database and this is more UI stuff. do we have a user story for playing comments that have already been recorded?

**Comment by sheesania** [comment]
@erica-zhong @dvmarchuk The database part of that is already in issue #67 . It's just the UI part of listing and playing comments that I don't think is represented in user stories

**Comment by erica-zhong** [comment]
@sheesania @dvmarchuk   i think that should be a new user story
