### ISSUE TITLE
Using Bad DB Data

### ISSUE THREAD

**Issue by Pinto18** [WycliffeAssociates/8woc2017#160]
I manually entered two fake takes, one with a fake book object and a location copied from another take, and another fake take with the same data as the other one except it also had a fake language object. All other fields for these fake takes were either left null, or automatically set to their default values. Each of the fields for the fake book and language were filled. **After creating the first fake take, I examined the behavior of Translation Manager. After navigating to the Projects Page, the filters loaded for an indefinite amount of time**. Then, I created the second fake take, and navigated to the Projects Page again. This time I was able to get the fake language to appear in the Language filter. After clicking on the fake language, the website navigated to a page which contained an error message. The software was expected to navigate to a page that contains an error message for both cases, but only fulfilled this requirement for the second test case. The software does not behave as expected.

**Comment by dvmarchuk** [comment]
Our manager is super smart. It know not to waste time on useless fake data.
