### ISSUE TITLE
Detect merge conflicts

### ISSUE THREAD

**Issue by annjones2** [WycliffeAssociates/8woc2017#35]
### User Story
As a manager, I want duplicate files to be uniquely named so that I know which ones are similar.

### Acceptance Criteria
- [x] implement UUID
- [x] see name changes in database

**Comment by ksigWyatt** [comment]
This story is not going to be affected, with the SQL Table setup implemented as well as the file system directory hierarchy. Attempting to implement some duplicate detection when accessing the database for multiple files.
